### ISSUE TITLE
Unable to activate - syntax error, unexpected ''

### ISSUE THREAD

**Issue by simonkilmore** [R-J/rj-like#2]
`syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) on Line 71`

There are further instances on line 105, 108 and 211.

Vanilla 3.3
PHP 7.2

**Comment by R-J** [comment]
There is no syntax error in those lines. Please try downloading the zip again and unpacking its content to /plugins/rj-like again.

**Comment by simonkilmore** [comment]
I'm not seeing any errors either but I've re-done it a couple of times, it keeps coming up when I try to activate in the dashboard, and running it through a PHP validator online it does seem to agree.

![](https://i.imgur.com/8P7TkYm.jpg)

**Comment by R-J** [comment]
Sorry, I forgot about that. Are you sure about your PHP version? Not sure about it, but if I remember it correctly, a construct like that `[$args['Discussion']->DiscussionID]` wasn't allowed with PHP 5.x

What do you mean by "and running it through a PHP validator online it does seem to agree."? I tried to find some online validators and they showed no error messages. I have pasted 
~~~
        echo '<style>.Reactions a.HasCount{display: inline-block}.Reactions .Count{border-radius:3px;margin-right:4px;vertical-align:top}</style>';

        $this->init();
        // Prefetch all posts that I like.
        $px = Gdn::database()->DatabasePrefix;
        $userID = Gdn::session()->UserID;
        $sql = <<< EOT
            SELECT CommentID
            FROM {$px}UserComment
            WHERE CommentID IN (
              SELECT CommentID
              FROM {$px}Comment
              WHERE DiscussionID = {$args['Discussion']->DiscussionID}
            )
            AND UserID = {$userID}
            AND RJ_Like = true
        EOT;
        $likedComments = Gdn::sql()->query($sql)->resultArray();
        $this->iLiked = [
            'Discussion' => [$args['Discussion']->DiscussionID],
            'Comment' => array_column($likedComments, 'CommentID')
        ];
~~~

at this page: https://phpcodechecker.com/ and it gave only the error you have reported, if I switched to PHP 5.6

**Comment by simonkilmore** [comment]
Yes, definitely running 7.2. Forum obviously wouldn't run at all if it was still 5.x since 3.3 requires 7.x. 

This validator is giving the same error with 7.x- https://www.piliapp.com/php-syntax-check/

**Comment by R-J** [comment]
That's a good link! It shows errors with PHP <= 7.2 and only validates for >= 7.3
Since 7.2 is not that outdated and the places where there are changes needed to make it work with 7.2, I'll make a quick fix soon. Thanks for your investigations!

**Comment by R-J** [comment]
Well... you can try to use that branch: https://github.com/R-J/rj-like/tree/fix/php-7.2-compatibility
If you give positive feedback, I will merge it.

That online validator above also parses comments, which is quite strange. The validators are giving me errors for `$comment = $args['Comment'];` which is why I doubt that what I did changed anything. But I really wouldn't know how to do it without that...

**Comment by simonkilmore** [comment]
Yes I just tried the new version on my forum and it's given the same error on that line you mention.

Just to clarify, my specific version of PHP is 7.2.27.

**Comment by R-J** [comment]
Honestly, what could be wrong with `$comment = $args['Comment'];`? I really do not know how to deal with that, sorry. Do you have the option to upgrade your PHP version?

**Comment by kbrookes** [comment]
Just popping in to say I was getting the same error on 7.2, but used cPanel's multiphp (which not all hosts use) to go to 7.3 and I was able to enable.

I cannot however actually click on the resulting like button :)

**Comment by meetdilip** [comment]
I installed today on my shared hosting with Vanilla 3.3 and got this error

`syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING)`

**Comment by R-J** [comment]
@meetdilip What's your php version? If it is 7.2 you should consider updating, not only because of this plugin: https://www.php.net/eol.php

**Comment by meetdilip** [comment]
> @meetdilip What's your php version? If it is 7.2 you should consider updating, not only because of this plugin: https://www.php.net/eol.php

Thanks. I am able to use `Like` when switched to v7.4. But I do not get any notifications for the Likes received. Is there anything we can do about it ?

**Comment by R-J** [comment]
That's not implemented, sorry

**Comment by meetdilip** [comment]
Thanks for the guidance. Hopefully I will able to find some method to receive notifications for appreciation.
